import {test,expect,type Page} from '@playwright/test'
const key='package-forge:v1'
async function applyScenario(p:Page,name:string){await p.getByRole('button',{name:new RegExp(`^${name}`)}).click();await p.getByRole('button',{name:'Review changed assumptions',exact:true}).click();await p.getByRole('button',{name:'Apply reviewed assumptions'}).click()}
async function review(p:Page,tier='Studio'){await p.getByRole('button',{name:`Review ${tier} quote`}).click()}
async function confirm(p:Page){await p.getByRole('button',{name:'Confirm local simulation'}).click()}
async function state(p:Page){return p.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key)}
test.beforeEach(async({page})=>{await page.goto('./')})
test('Cedar fit and traceable paid-editor price; preview cancel preserves commitments',async({page})=>{await expect(page.getByText('Lowest-cost fit:')).toContainText('Studio');await expect(page.getByRole('button',{name:'Review Base quote'})).toBeDisabled();await review(page);await expect(page.getByRole('dialog')).toContainText('$96.00 monthly');await expect(page.getByRole('dialog')).toContainText('2026-10-31');await page.getByRole('button',{name:'Cancel preview'}).click();expect((await state(page)).history).toHaveLength(0);expect((await state(page)).scheduled).toBe(null)})
test('annual calculation and commitment are explicit; baseline stays active',async({page})=>{await page.getByRole('radio',{name:'Annual commitment'}).check();await page.getByRole('button',{name:'Review changed assumptions',exact:true}).click();await page.getByRole('button',{name:'Apply reviewed assumptions'}).click();await review(page);await expect(page.getByRole('dialog')).toContainText('$960.00 for an annual commitment');await expect(page.getByRole('dialog')).toContainText('$80.00 — comparison only; charged annually');await expect(page.getByRole('dialog')).toContainText('2027-10-31');await confirm(page);await expect(page.getByRole('region',{name:'Studio · 8 paid editors, 24 free viewers',exact:true})).toContainText('$96.00 actual monthly charge');await expect(page.getByText('Studio scheduled · Q1')).toBeVisible();await page.reload();expect((await state(page)).history[0].charge).toBe(96000)})
test('Archive upgrade meets audit needs and charges actual annual amount',async({page})=>{await applyScenario(page,'Harbor Records');await review(page,'Archive');await expect(page.getByRole('dialog')).toContainText('Upgrade.');await expect(page.getByRole('dialog')).toContainText('$2,880.00');await expect(page.getByRole('dialog')).toContainText('No capability or package-capacity loss.');await confirm(page);expect((await state(page)).scheduled).toBe('Q1')})
test('downgrade lists lost approval and exact capacities before cancel or confirm',async({page})=>{await applyScenario(page,'Kite Collective');await review(page,'Base');const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Downgrade.');await expect(dialog).toContainText('Approval workflows');await expect(dialog).toContainText('Editor capacity: 20 → 3');await expect(dialog).toContainText('Viewer capacity: 200 → 20');await expect(dialog).toContainText('$0.00 monthly');await page.getByRole('button',{name:'Cancel preview'}).click();expect((await state(page)).scheduled).toBe(null);await review(page,'Base');await confirm(page);expect((await state(page)).history[0].tier).toBe('base')})
test('schedule cancellation retains history and never restores prior schedule',async({page})=>{await review(page);await confirm(page);await review(page,'Archive');await confirm(page);await page.getByRole('button',{name:'Cancel scheduled change'}).click();await page.getByRole('button',{name:'Confirm schedule cancellation'}).click();const s=await state(page);expect(s.scheduled).toBe(null);expect(s.history).toHaveLength(2);expect(s.canceled).toEqual(['Q2']);await expect(page.getByText('No change scheduled.')).toBeVisible();await expect(page.getByText('Q1 · Studio · $96.00 monthly · Superseded schedule')).toBeVisible()})
test('replacement explicitly names prior quote and cancel preserves it',async({page})=>{await review(page);await confirm(page);const prior=(await state(page)).history[0];await review(page,'Archive');await expect(page.getByRole('dialog')).toContainText('replaces scheduled Q1');await page.getByRole('button',{name:'Cancel preview'}).click();expect((await state(page)).scheduled).toBe('Q1');await review(page,'Archive');await confirm(page);const s=await state(page);expect(s.history[0]).toEqual(prior);expect(s.scheduled).toBe('Q2');expect(s.canceled).toEqual([])})
test('overflow blocks all quotes and gives honest no-fit',async({page})=>{await applyScenario(page,'Widefield Network');await expect(page.getByText('No package fits these needs.')).toBeVisible();for(const n of ['Base','Studio','Archive'])await expect(page.getByRole('button',{name:`Review ${n} quote`})).toBeDisabled();await expect(page.getByText('Lowest-cost fit:')).toHaveCount(0)})
test('must-have removal is separately reviewed and cancel does not apply it',async({page})=>{await page.getByRole('checkbox',{name:'Approval workflows',exact:true}).uncheck();await page.getByRole('button',{name:'Review changed assumptions',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Removing a required capability is an intentional scope change');await page.getByRole('button',{name:'Cancel preview'}).click();expect((await page.getByRole('button',{name:'Review Studio quote'}).isDisabled())).toBe(true);await page.getByRole('button',{name:'Discard edits'}).click();await expect(page.getByRole('checkbox',{name:'Approval workflows',exact:true})).toBeChecked()})
test('one-step assumptions Undo does not rewrite commitments',async({page})=>{await review(page);await confirm(page);const before=await state(page);await page.getByRole('spinbutton',{name:'Paid editors',exact:true}).fill('9');await page.getByRole('button',{name:'Review changed assumptions',exact:true}).click();await page.getByRole('button',{name:'Apply reviewed assumptions'}).click();await page.getByRole('button',{name:'Undo last assumptions'}).click();const after=await state(page);expect(after.draft.editors).toBe(8);expect(after.history).toEqual(before.history);expect(after.scheduled).toBe('Q1');await expect(page.getByRole('button',{name:'Undo last assumptions'})).toHaveCount(0)})
test('invalid counts block applied scope and keep compatible saved state',async({page})=>{for(const value of ['-1','1.5','10001','']){await page.getByRole('spinbutton',{name:'Paid editors',exact:true}).fill(value);await expect(page.getByRole('button',{name:'Review changed assumptions',exact:true})).toBeDisabled();await expect(page.getByText('Enter whole editor')).toBeVisible()}await page.reload();await expect(page.getByRole('spinbutton',{name:'Paid editors',exact:true})).toHaveValue('8')})
test('zero paid editors allows illustrative viewer-only $0 subject to fit',async({page})=>{await page.getByRole('spinbutton',{name:'Paid editors',exact:true}).fill('0');await page.getByRole('button',{name:'Review changed assumptions',exact:true}).click();await page.getByRole('button',{name:'Apply reviewed assumptions'}).click();await review(page);await expect(page.getByRole('dialog')).toContainText('$0.00 monthly');await expect(page.getByRole('dialog')).toContainText('0 / 24 · Viewers $0')})
test('compatible refresh preserves confirmed history and scheduled assumptions',async({page})=>{await review(page);await confirm(page);const before=await state(page);await page.reload();expect(await state(page)).toEqual(before);await expect(page.getByText('Studio scheduled · Q1')).toBeVisible()})
for(const raw of ['{bad','{"schema":99}','{"schema":1,"revision":0,"draft":{"editors":8,"viewers":24,"needs":[],"cycle":"monthly"},"selected":null,"history":[],"scheduled":"Q999","canceled":[]}'])test(`preserve invalid storage and explicit reset: ${raw.slice(0,20)}`,async({page})=>{await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key,raw});await page.reload();await expect(page.getByRole('alert')).toContainText('preserved');expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(raw);await page.getByRole('button',{name:'Preview sample reset'}).click();await page.getByRole('button',{name:'Cancel preview'}).click();expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(raw);await page.getByRole('button',{name:'Preview sample reset'}).click();await page.getByRole('button',{name:'Confirm sample reset'}).click();expect((await state(page)).history).toEqual([]);await expect(page.getByRole('alert')).toHaveCount(0)})
test('external same-revision content change rejects pending quote',async({page})=>{await review(page);await page.evaluate(k=>{const s=JSON.parse(localStorage.getItem(k)!);s.draft.editors=9;localStorage.setItem(k,JSON.stringify(s))},key);await confirm(page);await expect(page.getByRole('status')).toContainText('Preview rejected');expect((await state(page)).history).toHaveLength(0);await expect(page.getByRole('alert')).toContainText('changed outside')})
test('cross-tab corruption rejects pending quote and reset remains accessible',async({page,context})=>{await review(page);const other=await context.newPage();await other.goto('./');await other.evaluate(k=>localStorage.setItem(k,'external-corruption'),key);await expect(page.getByRole('alert')).toContainText('changed outside');await confirm(page);await page.getByRole('button',{name:'Preview sample reset'}).click();await page.getByRole('button',{name:'Confirm sample reset'}).click();expect((await state(page)).scheduled).toBe(null);await other.close()})
for(const mode of ['getter','read','write'])test(`unavailable storage ${mode} keeps memory and warns`,async({page})=>{await page.addInitScript(mode=>{if(mode==='getter')Object.defineProperty(window,'localStorage',{get(){throw Error('denied')}});else Object.defineProperty(Storage.prototype,mode==='read'?'getItem':'setItem',{value(){throw Error('denied')}})},mode);await page.reload();await review(page);await confirm(page);await expect(page.getByRole('alert')).toContainText('memory');await expect(page.getByText('Studio scheduled · Q1')).toBeVisible()})
test('dialog traps Tab and reverse Tab, Escape cancels with focus restored',async({page})=>{await review(page);const close=page.getByRole('button',{name:'Close preview'}),last=page.getByRole('button',{name:'Confirm local simulation'});await expect(close).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(last).toBeFocused();await page.keyboard.press('Tab');await expect(close).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Review Studio quote'})).toBeFocused()})
test('new editor and quote are visible at 1280x633; opener fallback survives',async({page})=>{await page.getByRole('button',{name:/^Kite Collective/}).click();await expect(page.getByRole('spinbutton',{name:'Paid editors',exact:true})).toBeFocused();const box=await page.getByRole('spinbutton',{name:'Paid editors',exact:true}).boundingBox();expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.y+box!.height).toBeLessThan(633);await page.getByRole('button',{name:'Review changed assumptions',exact:true}).click();await page.getByRole('button',{name:'Apply reviewed assumptions'}).click();await expect(page.getByRole('heading',{name:'A package that fits the way you work.'})).toBeFocused();await review(page,'Base');await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:'evidence/desktop-quote.png'})})
for(const width of [320,390])test(`mobile ${width} has no overflow and reachable quote controls`,async({page})=>{await page.setViewportSize({width,height:844});await page.reload();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await applyScenario(page,'Kite Collective');await review(page,'Base');await expect(page.getByRole('dialog')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Confirm local simulation'}).scrollIntoViewIfNeeded();await page.screenshot({path:`evidence/mobile-${width}.png`});await confirm(page);await expect(page.getByText('Base scheduled · Q1')).toBeVisible()})
test('production has no console/page errors or external app requests; docs work',async({page})=>{const errors:string[]=[],external:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4191/'))external.push(r.url())});await page.reload();await review(page);await page.keyboard.press('Escape');for(const file of ['Product_Brief','PRD','Sample_Contract','Case_Study','Decisions_and_Risks','Validation','Sample_Walkthrough']){const response=await page.request.get(`docs/product/${file}.md`);expect(response.status()).toBe(200)}expect(errors).toEqual([]);expect(external).toEqual([])})
