import {useCallback,useEffect,useRef,useState} from 'react'
import {BASELINE,CATALOG,CLOCK,FEATURES,SCENARIOS,TIERS,cancelScheduled,confirm,cost,fit,losses,money,quote,seed,validDraft,type Draft,type Feature,type Quote,type State,type TierId} from './domain'
import {LocalStore,STORAGE_KEY,type ResetToken} from './storage'
import {Modal} from './Modal'
type Form={editors:string;viewers:string;needs:Feature[];cycle:Draft['cycle']}
const formOf=(d:Draft):Form=>({...d,editors:String(d.editors),viewers:String(d.viewers),needs:[...d.needs]})
const draftOf=(f:Form):Draft=>({...f,editors:f.editors.trim()===''?NaN:Number(f.editors),viewers:f.viewers.trim()===''?NaN:Number(f.viewers)})
type Preview={type:'quote';q:Quote;formKey:string}|{type:'draft';d:Draft}|{type:'reset';token:ResetToken|null}|{type:'cancel'}
export default function App(){
 const [store]=useState(()=>new LocalStore());const [s,setState]=useState(store.state);const [form,setForm]=useState(()=>formOf(store.state.draft));const [preview,setPreview]=useState<Preview|null>(null);const [notice,setNotice]=useState('Choose needs, compare fit, then review the renewal change.');const [warning,setWarning]=useState(store.warning);const [undo,setUndo]=useState<Draft|null>(null);const editor=useRef<HTMLElement>(null)
 const close=useCallback(()=>{setPreview(null)},[])
 useEffect(()=>{const external=(event:StorageEvent)=>{if(event.key===STORAGE_KEY||event.key===null){store.check();setWarning(store.warning);setNotice('An external saved-state change needs recovery before confirmation.')}};window.addEventListener('storage',external);return()=>window.removeEventListener('storage',external)},[store])
 const apply=(next:State,reset=false,token?:ResetToken|null)=>{const ok=store.save(next,reset,token);setWarning(store.warning);if(ok)setState(next);else setNotice('Saved-state conflict: your current plan and history were preserved.');return ok}
 const openReset=()=>{const token=store.captureReset();setWarning(store.warning);setPreview({type:'reset',token})}
 const d=draftOf(form), valid=validDraft(d), dirty=JSON.stringify(form)!==JSON.stringify(formOf(s.draft)), matches=TIERS.filter(t=>fit(t.id,s.draft).length===0)
 const scheduled=s.history.find(q=>q.id===s.scheduled)
 const openQuote=(tier:TierId)=>{if(dirty||!valid){setNotice('Review and apply the changed assumptions first.');return}const next={...s,selected:tier,revision:s.revision+1};if(apply(next))setPreview({type:'quote',q:quote(next,tier),formKey:JSON.stringify(form)})}
 const chooseScenario=(id:string)=>{const scenario=SCENARIOS.find(x=>x.id===id)!;setForm(formOf(scenario.draft));setNotice(`${scenario.name}: review these assumptions before applying.`);editor.current?.scrollIntoView({block:'start',behavior:'smooth'});document.getElementById('editors')?.focus()}
 const execute=()=>{
  if(!preview)return
  if(preview.type==='reset'){if(apply(seed(),true,preview.token)){setForm(formOf(seed().draft));setUndo(null);setNotice('Sample reset: history and scheduled changes cleared. The fictional active baseline is Studio.');setPreview(null)}return}
  if(!store.check()){setWarning(store.warning);setNotice('Preview rejected: saved state changed. Recover before continuing.');setPreview(null);return}
  if(preview.type==='draft'){setUndo(structuredClone(s.draft));const next={...s,draft:structuredClone(preview.d),selected:null,revision:s.revision+1};if(apply(next)){setForm(formOf(next.draft));setNotice('Assumptions applied. Select a fitting package to create a fresh quote.');setPreview(null)}}
  if(preview.type==='cancel'){if(apply(cancelScheduled(s))){setUndo(null);setNotice('Scheduled change canceled. Active Studio baseline and confirmed quote history retained.');setPreview(null)}}
  if(preview.type==='quote'){try{if(preview.formKey!==JSON.stringify(form))throw new Error('Draft changed');const next=confirm(s,preview.q);if(apply(next)){setUndo(null);setNotice(`${preview.q.id} confirmed as a local simulation, effective ${preview.q.effective}. No payment or subscription was changed.`);setPreview(null)}}catch{setNotice('Preview rejected: assumptions, selection, or quote version changed. Create a fresh quote.');setPreview(null)}}
 }
 return <><header><a className="brand" href="#worksheet"><span className="brand-mark">▱</span> Package Forge</a><span className="eyebrow">NORTHSTAR / PACKAGING WORKSHEET</span><a href="docs/product/Case_Study.html">Product story ↗</a></header><main id="worksheet">
 <div className="intro"><div><span className="kicker">FIT FIRST. COST CLEAR.</span><h1 id="worksheet-title" tabIndex={-1}>A package that fits<br/>the way you work.</h1><p>Start with your team's must-haves. Compare illustrative prices, then review exactly what changes at renewal.</p></div><aside className="boundary"><span className="dot"/> Fictional local simulation<p>All prices are illustrative USD. No payment, subscription, tax, refund, or proration is processed.</p><small>Sample clock {CLOCK} · Catalog {CATALOG}</small></aside></div>
 <div className="status" role="status" aria-live="polite">{notice}</div>{warning?<div role="alert" className="warning">{warning} <button onClick={()=>window.location.reload()}>Reload saved data</button> <button onClick={openReset}>Preview reset</button></div>:null}
 <section className="current" aria-labelledby="current-title"><div><span className="kicker">ACTIVE / FICTIONAL BASELINE</span><h2 id="current-title">Studio · 8 paid editors, 24 free viewers</h2><p>{money(BASELINE.charge)} actual monthly charge · Next renewal <strong>{BASELINE.renewal}</strong></p><small>Baseline {BASELINE.version} · 20-editor / 200-viewer capacity · Shared boards + Approval workflows</small></div><div className="scheduled"><span className="kicker">NEXT RENEWAL</span>{scheduled?<><h3>{TIERS.find(t=>t.id===scheduled.tier)?.name} scheduled · {scheduled.id}</h3><p>{money(scheduled.charge)} {scheduled.draft.cycle==='annual'?'annual':'monthly'} charge on {scheduled.effective}</p><button className="secondary" onClick={()=>setPreview({type:'cancel'})}>Cancel scheduled change</button></>:<p>No change scheduled.<br/>The active plan stays Studio.</p>}</div></section>
 <section className="scenario-section"><div className="section-heading"><span className="step">01</span><h2>Start with a fictional team</h2></div><div className="scenarios">{SCENARIOS.map(x=><button key={x.id} className="scenario" onClick={()=>chooseScenario(x.id)}><strong>{x.name}</strong><span>{x.context}</span><small>Load assumptions ↗</small></button>)}</div></section>
 <section ref={editor} className="worksheet-grid" aria-labelledby="needs-title"><div className="editor"><div className="section-heading"><span className="step">02</span><h2 id="needs-title">Your team's needs</h2></div><p>Editors are paid seats on paid tiers. Viewers cost $0 on every tier and never enter the paid count. This hypothetical catalog has no minimum seat fee: zero editors means $0, subject to fit.</p><div className="counts"><label htmlFor="editors">Paid editors<input id="editors" type="number" min="0" max="10000" step="1" value={form.editors} onChange={e=>setForm({...form,editors:e.target.value})}/></label><label htmlFor="viewers">Free viewers<input id="viewers" type="number" min="0" max="10000" step="1" value={form.viewers} onChange={e=>setForm({...form,viewers:e.target.value})}/></label></div><fieldset><legend>Must-have capabilities</legend>{FEATURES.map(n=><label className="check" key={n}><input type="checkbox" checked={form.needs.includes(n)} onChange={e=>setForm({...form,needs:e.target.checked?[...form.needs,n]:form.needs.filter(x=>x!==n)})}/>{n}</label>)}</fieldset><fieldset className="cycle"><legend>Billing term</legend>{(['monthly','annual'] as const).map(c=><label key={c}><input type="radio" name="cycle" checked={form.cycle===c} onChange={()=>setForm({...form,cycle:c})}/>{c==='monthly'?'Monthly':'Annual commitment'}</label>)}</fieldset>{!valid?<p className="error" role="alert">Enter whole editor and viewer counts from 0 to 10,000.</p>:null}<button className="primary" disabled={!dirty||!valid} onClick={()=>setPreview({type:'draft',d})}>Review changed assumptions</button>{dirty?<button onClick={()=>{setForm(formOf(s.draft));setNotice('Unapplied edits discarded.')}}>Discard edits</button>:null}{undo&&!dirty?<button onClick={()=>{const prior=undo;if(apply({...s,draft:prior,selected:null,revision:s.revision+1})){setForm(formOf(prior));setUndo(null);setNotice('Last assumptions restored. Quotes and active baseline were not changed.')}}}>Undo last assumptions</button>:null}<small>Undo covers one applied assumptions change, until a commitment action or refresh.</small></div>
 <div className="comparison"><div className="section-heading"><span className="step">03</span><h2>Compare your packages</h2></div><p className="applied">Applied: {s.draft.editors} editors + {s.draft.viewers} free viewers · {s.draft.cycle}{dirty?' · Unapplied changes require review':''}</p>{matches.length===0?<div className="no-fit" role="status"><strong>No package fits these needs.</strong><p>Capacity or required capabilities are missing. Change scope only through a separate assumptions review; confirmation is blocked.</p></div>:<p className="recommend">Lowest-cost fit: <strong>{matches[0].name}</strong> · Every must-have and capacity requirement is met.</p>}
 <div className="tiers">{TIERS.map(t=>{const gaps=fit(t.id,s.draft),c=cost(t.id,s.draft);return <article className={`tier ${gaps.length?'unfit':'fit'}`} key={t.id}><div className="tier-title"><h3>{t.name}</h3><span>{gaps.length?'Does not fit':'Fits needs'}</span></div><p>{t.note}</p><div className="price">{money(c.charge)}<span>actual {s.draft.cycle==='annual'?'annual commitment':'monthly charge'}</span></div>{s.draft.cycle==='annual'?<p>{money(c.equivalentMonthly)} equivalent / month<br/>Charged annually, not monthly.</p>:null}<small>{s.draft.editors} × {money(s.draft.cycle==='annual'?t.annualMonthly:t.monthly)}{s.draft.cycle==='annual'?' × 12 months':''} + viewers $0</small><p className="capacity">Up to {t.editors} editors / {t.viewers} viewers</p><ul>{FEATURES.map(n=><li key={n}>{(t.features as readonly Feature[]).includes(n)?'✓':'—'} {n}</li>)}</ul>{gaps.length?<ul className="gaps">{gaps.map(g=><li key={g}>{g}</li>)}</ul>:null}<button className={gaps.length?'secondary':'primary'} disabled={!!gaps.length||dirty||s.history.length>=100} onClick={()=>openQuote(t.id)}>Review {t.name} quote</button></article>})}</div></div></section>
 <section className="history"><div className="section-heading"><span className="step">04</span><h2>Confirmed quote record</h2></div>{s.history.length>=100?<p className="warning">The 100-quote sample history is full. Confirmation is blocked; preview reset to clear it after review.</p>:null}<p>Confirmed assumptions remain immutable. Scheduling a replacement retains older quotes; canceling a schedule does not revive an older one.</p>{s.history.length===0?<p className="empty">No confirmed quotes yet. Draft changes are not commitments.</p>:s.history.map(q=><details key={q.id}><summary>{q.id} · {TIERS.find(t=>t.id===q.tier)?.name} · {money(q.charge)} {q.draft.cycle} · {s.scheduled===q.id?'Scheduled':s.canceled.includes(q.id)?'Canceled schedule':'Superseded schedule'}</summary><p>{q.draft.editors} editors, {q.draft.viewers} free viewers · Must-haves: {q.draft.needs.join(', ')||'None'}.</p><p>Effective {q.effective} · Term ends {q.termEnd} · {q.catalog} / quote v{q.version} / baseline {q.baseline} / assumptions revision {q.revision}</p><p>Quoted at fixed {q.clock}; valid through {q.expires}. Confirmation is a local simulation.</p></details>)}</section>
 <footer><div><strong>Clear boundaries make a better choice.</strong><p>Mo: product and program direction. AI assisted implementation and software verification. Fictional samples; human evaluation is proposed.</p></div><div><button onClick={openReset}>Preview sample reset</button><a href="docs/product/Sample_Walkthrough.html">Walkthrough ↗</a><a href="docs/product/Validation.html">Evidence and limits ↗</a></div></footer>
 </main>{preview?<Modal title={preview.type==='quote'?'Review renewal change':preview.type==='draft'?'Review changed assumptions':preview.type==='cancel'?'Cancel the scheduled change?':'Reset this local sample?'} onCancel={close} actions={<div className="dialog-actions"><button className="secondary" onClick={close}>Cancel preview</button><button className="primary" onClick={execute}>{preview.type==='quote'?'Confirm local simulation':preview.type==='draft'?'Apply reviewed assumptions':preview.type==='cancel'?'Confirm schedule cancellation':'Confirm sample reset'}</button></div>}>
 {preview.type==='quote'?<><p className="kicker">{preview.q.id} · QUOTE V{preview.q.version} · {preview.q.catalog}</p><h3>Studio → {TIERS.find(t=>t.id===preview.q.tier)?.name}</h3><p>{TIERS.findIndex(t=>t.id===preview.q.tier)<1?'Downgrade':TIERS.findIndex(t=>t.id===preview.q.tier)>1?'Upgrade':'Same package / revised assumptions or term'}. Active Studio stays unchanged until the fictional next renewal.</p><dl><dt>Effective date</dt><dd>{preview.q.effective} (next renewal)</dd><dt>Actual charge</dt><dd>{money(preview.q.charge)} {preview.q.draft.cycle==='annual'?'for an annual commitment':'monthly'}</dd><dt>Term ends</dt><dd>{preview.q.termEnd}</dd><dt>Equivalent monthly</dt><dd>{money(preview.q.equivalentMonthly)}{preview.q.draft.cycle==='annual'?' — comparison only; charged annually':''}</dd><dt>Paid seats / free viewers</dt><dd>{preview.q.draft.editors} / {preview.q.draft.viewers} · Viewers $0</dd></dl><h3>Capabilities and capacity lost</h3>{losses(preview.q.tier).length?<ul className="losses">{losses(preview.q.tier).map(l=><li key={l}>{l}</li>)}</ul>:<p>No capability or package-capacity loss.</p>}<p>Quote valid through {preview.q.expires} against fixed sample clock {CLOCK}. Must-haves: {preview.q.draft.needs.join(', ')||'None'}. {scheduled?`Confirmation replaces scheduled ${scheduled.id}; its immutable quote stays in history as superseded. Cancel preview keeps ${scheduled.id} scheduled.`:''}</p><div className="simulation">Local simulation only. No payment, real subscription, immediate charge, or proration.</div></>:null}
 {preview.type==='draft'?<><p>Applying this scope creates a new assumptions revision and clears the selected package. Scenarios change the proposed renewal team, not the fixed active Studio baseline. Current and scheduled plans keep their confirmed assumptions.</p><dl><dt>Editors</dt><dd>{s.draft.editors} → {preview.d.editors}</dd><dt>Free viewers</dt><dd>{s.draft.viewers} → {preview.d.viewers}</dd><dt>Must-haves before</dt><dd>{s.draft.needs.join(', ')||'None'}</dd><dt>Must-haves after</dt><dd>{preview.d.needs.join(', ')||'None'}</dd><dt>Term</dt><dd>{s.draft.cycle} → {preview.d.cycle}</dd></dl><p>Removing a required capability is an intentional scope change, not a cheaper package satisfying the old needs.</p></>:null}
 {preview.type==='cancel'?<p>Remove only {scheduled?.id}'s scheduled next-renewal change. Keep the active Studio baseline, draft and immutable confirmed quotes. No earlier schedule is restored. This cancellation cannot be undone; create a fresh quote to schedule again.</p>:null}
 {preview.type==='reset'?<><p>Replace saved data with the original Cedar sample. Clear all confirmed quote history, scheduled changes, selections and Undo. The original fictional active Studio baseline remains.</p><p>Unknown or corrupt saved data is preserved until you confirm this reset. Confirmation rejects any saved-data change after this preview; unreadable or unwritable data remains preserved. Reset cannot be undone.</p></>:null}
 </Modal>:null}</>
}
