import {afterEach,expect,it,vi} from 'vitest'
import {LocalStore,STORAGE_KEY} from './storage'
import {confirm,quote,seed} from './domain'
afterEach(()=>vi.unstubAllGlobals())
function storage(raw:string|null=null){const data=new Map<string,string>();if(raw!==null)data.set(STORAGE_KEY,raw);const api={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v)}};vi.stubGlobal('window',{localStorage:api});return {data,api}}
it('compatible refresh loads exact memory',()=>{storage(JSON.stringify(seed()));expect(new LocalStore().state).toEqual(seed())})
it('unknown storage survives ordinary save',()=>{const {data}=storage('{bad');const st=new LocalStore();expect(st.save(seed())).toBe(false);expect(data.get(STORAGE_KEY)).toBe('{bad');expect(st.save(seed(),true,st.captureReset())).toBe(true)})
it('same revision different content rejects a pending mutation',()=>{const {api}=storage(JSON.stringify(seed()));const st=new LocalStore();api.setItem(STORAGE_KEY,JSON.stringify({...seed(),draft:{...seed().draft,editors:9}}));expect(st.save({...seed(),revision:1})).toBe(false);expect(st.state.draft.editors).toBe(8)})
it('external corruption preserves current memory and raw until reset',()=>{const {data}=storage();const st=new LocalStore();st.save({...seed(),revision:1});data.set(STORAGE_KEY,'corrupt');expect(st.check()).toBe(false);expect(st.state.revision).toBe(1);expect(data.get(STORAGE_KEY)).toBe('corrupt');st.save(seed(),true,st.captureReset());expect(data.get(STORAGE_KEY)).toBe(JSON.stringify(seed()))})
it('localStorage getter exception retains work in memory',()=>{vi.stubGlobal('window',Object.defineProperty({},'localStorage',{get(){throw Error('denied')}}));const st=new LocalStore();expect(st.save({...seed(),revision:1})).toBe(true);expect(st.state.revision).toBe(1);expect(st.warning).toContain('memory')})
it('getItem read exception retains work in memory',()=>{vi.stubGlobal('window',{localStorage:{getItem(){throw Error('denied')},setItem(){throw Error('denied')}}});const st=new LocalStore();st.save({...seed(),revision:2});expect(st.state.revision).toBe(2);expect(st.warning).toContain('memory')})
it('write exception retains current memory and explains persistence',()=>{const {api}=storage();api.setItem=()=>{throw Error('quota')};const st=new LocalStore();st.save({...seed(),revision:3});expect(st.state.revision).toBe(3);expect(st.warning).toContain('cannot be written')})

it('read exception warning persists even if a write succeeds',()=>{const {api}=storage();api.getItem=()=>{throw Error('denied')};const st=new LocalStore();expect(st.save({...seed(),revision:2})).toBe(true);expect(st.warning).toContain('memory')})
it('rejects a revision above the supported bound without corrupting memory',()=>{storage();const st=new LocalStore();expect(st.save({...seed(),revision:1000001})).toBe(false);expect(st.state.revision).toBe(0)})

it('unreadable storage never writes unseen original bytes',()=>{const {api,data}=storage('unseen-original');api.getItem=()=>{throw Error('denied')};const writer=vi.spyOn(api,'setItem');const st=new LocalStore();st.save({...seed(),revision:1});expect(writer).not.toHaveBeenCalled();expect(data.get(STORAGE_KEY)).toBe('unseen-original')})
it('reset rejects raw changes after preview; fresh corruption reset works',()=>{const {data}=storage('old-corrupt');const st=new LocalStore();const token=st.captureReset();data.set(STORAGE_KEY,'new-corrupt');expect(st.save(seed(),true,token)).toBe(false);expect(data.get(STORAGE_KEY)).toBe('new-corrupt');expect(st.save(seed(),true,st.captureReset())).toBe(true)})
it('unreadable or unwritable reset preserves original bytes and memory',()=>{const {api,data}=storage('corrupt');const st=new LocalStore();const token=st.captureReset();api.setItem=()=>{throw Error('quota')};expect(st.save(seed(),true,token)).toBe(false);expect(data.get(STORAGE_KEY)).toBe('corrupt');api.getItem=()=>{throw Error('denied')};expect(st.save(seed(),true,token)).toBe(false);expect(data.get(STORAGE_KEY)).toBe('corrupt')})

it.each([['expires','2026-10-01','expired'],['catalog','old-v0','stale']])('explains invalid saved quote %s', (field,value,label)=>{const s={...seed(),selected:'studio' as const};const n=confirm(s,quote(s,'studio'));Object.assign(n.history[0],{[field]:value});storage(JSON.stringify(n));const st=new LocalStore();expect(st.warning).toContain(label);expect(st.blocked).toBe(true)})
